### ISSUE TITLE
Entity threw exception at world: / NegativeArraySizeException

### ISSUE THREAD

**Issue by assasin541** [TacoSpigot/TacoSpigot#110]
[15:57:29] [Server thread/WARN]: Entity threw exception at world:-0.4748091139715158,60.0,-0.36479610581665933
[15:57:29] [Server thread/WARN]: java.lang.NegativeArraySizeException
[15:57:29] [Server thread/WARN]: 	at java.util.AbstractCollection.toArray(AbstractCollection.java:136)
[15:57:29] [Server thread/WARN]: 	at java.util.ArrayList.addAll(ArrayList.java:581)
[15:57:29] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.EntityPlayer.t_(EntityPlayer.java:242)
[15:57:29] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1510)
[15:57:29] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.World.g(World.java:1485)
[15:57:29] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1361)
[15:57:29] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:600)
[15:57:29] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:848)
[15:57:29] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[15:57:29] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715)
[15:57:29] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618)
[15:57:29] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

What can cause this and how to fix that?

**Comment by assasin541** [comment]
How to get taco source code with classes? nms, bukkit, craftbukkit? Like src of whole jar?

**Comment by MacacoLew** [comment]
Clone the repository, run ./build.sh and, AMAZING U HAVE THE SRC OMG

**Comment by assasin541** [comment]
@MacacoLew I want 1.8 version

**Comment by assasin541** [comment]
@MacacoLew git clone https://github.com/TacoSpigot/TacoSpigot/tree/010c6514734b9676bcb26b36f5290e1a013873bd
Cloning into '010c6514734b9676bcb26b36f5290e1a013873bd'...
fatal: repository 'https://github.com/TacoSpigot/TacoSpigot/tree/010c6514734b9676bcb26b36f5290e1a013873bd/' not found

**Comment by assasin541** [comment]
@MacacoLew when I downloaded zip and initialized git I have this error:
root@ns3139385:~/TacoSpigot2# ./build.sh
cat: BuildData/info.json: No such file or directory
cat: BuildData/info.json: No such file or directory
cat: BuildData/info.json: No such file or directory
cat: BuildData/info.json: No such file or directory
cat: BuildData/info.json: No such file or directory
cat: BuildData/info.json: No such file or directory
Downloading unmapped vanilla jar...
The MD5 checksum of the downloaded server jar does not match the BuildData hash.

**Comment by andreasdc** [comment]
@Techcable I thought there is some work going on this project when I saw this message :(

**Comment by Techcable** [comment]
> @Techcable I thought there is some work going on this project when I saw this message :(

If you're referring to newer versions, I think Paper has most of Taco's patches at this point.

If there is anything missing get in touch and I'll provide advice on porting it.

If you're referring to 1.8, I think the amount of effort required to support it is not worth the effort.

At this point, proper support would require:
1. Finding and fixing security vulnerabilities
2. Finding and fixing bugs
3. Supporting and modifying plugins. Due to significant API changes between 1.8 and modern minecraft, almost *every plugin* would require significant changes.
    - This means an *experienced* developer would have to modify and edit almost every plugin (decompiling and deobfuscating the closed source ones)
    - in many cases this would also require modifying data files/formats

To properly do all these things would require hiring a full time developer. This developer would have to have experience both with server implementation and bukkit plugins.

There are very few servers who have the resources to pay for this, and not many developers would be able to and willing to do this.

As for the current forks of TacoSpigot 1.8, they seem to fall into two main categories:
1. Free forks
     - Most of these seem to have good intentions, but are very often inexperienced devs.
        - In particular, many of these forks cause severe bugs while trying to improve performance. They will try ridiculous things like "async mob processing" without any proper care for thread safety.....
     - These almost always have severe problems with *plugin compatibility* (see point 3 above). Even basic plugins like Factions and Essentials have problems. Plugins that use NMS internals (like Citizens) are almost impossible to get working.
         - Since most of these plugins have dropped 1.8 support by now
         - Developers of mainstream plugins are just tired of supporting 1.8, especially developers who work for free (like me)
2. Paid forks
      - 80% to 90% of the time these are scams or people looking to make a quick buck (especially on McMarket).
          - They tend to have severe problems with stability, because these developers care more about your money than your data
      - The other 10% of the time, you have a private contract with an experienced developer 
          - These private developers are typically on call 24/7 if your server crashes or gets an item duplication/security issue.
          - in addition to reliable support, these private contractors have to go through a massive amount of effort to get plugin compatibility working (in addition to bug fixes)

**TLDR**; Supporting 1.8 is a full time job. A few massive servers can afford these full time private devs. It is not something I am willing to do (especially not for free).

#### Alternatives
If you still want to support 1.8 clients, it is possible to use ProtocolSupport to allow them to connect to modern servers.

As for PVP mechanics, there are some plugins and server patches that can emulate this on modern servers. Patching Paper's PVP mechanics (or even running a custom fork) is still easier  than fixing all the bugs and compatibility problems with 1.8

Also, as far as I'm aware, Paper's performance in 1.17 should have caught up with Taco 1.8 by now :)
