### ISSUE TITLE
Security exploits?

### ISSUE THREAD

**Issue by andreasdc** [TacoSpigot/TacoSpigot#116]
"There are multiple confirmed security exploits that will allow item duplication and even server takeover."

Where are they confirmed?

**Comment by Techcable** [comment]
In terms of security problems, I am mostly referring to item duplication bugs, denial of service attacks, and privilege escalation (gaining OP).

I don't want to release the ones I know about and it's not my job to track down the ones I don't know about. 😉

Modern Paper is extremely careful about security and item duplication, yet I still see a (private) channel that is regularly full of exploit reports.

Modern Paper has a large and experinced development team that quickly fixes any exploits that arise.

Unless you are paying for a private developer, there is no similarly reliable l source for 1.8

I would also like to add that very often TacoSpigot forks that claim to fix bugs, end up introducing even more bugs in the process. 

The forks that claim to offer performance improvements are even scarier, they demonstrate a complete misunderstanding of thread safety. You - can't just make things async and expect things to work without bugs. To be thread safe, code must be written from the start with it in mind (or be carefully modified by an expert who is closely monitoring for bugs).

Closing because TacoSpigot 1.8 *is* insecure and all the forks are even worse.
